### ISSUE TITLE
Pypi repository

### ISSUE THREAD

**Issue by kylegodbey** [odell/rose#18]
We will want this to be pip-installable down the road -- any opinions on the package name for the `pip install ____`? Pretty sure `rose` is taken

**Comment by odell** [comment]
Options (in no particular order):
• `rose-band`
• `la-rosa`
• `rosado`
... I'll keep thinking about it.

**Comment by odell** [comment]
`nuclear-rose` sounds very metal – I like it. Goes great with @pabggpnMSU 's hair.

**Comment by odell** [comment]
The hardest part for me is not spending too much time on it. When I caught myself looking up the national flower of Venezuala earlier today, I realized I was going too far.

**Comment by odell** [comment]
`rose` is now [available on PyPI](https://pypi.org/project/nuclear-rose/).
