### ISSUE TITLE
Add support for Coulomb.

### ISSUE THREAD

**Issue by odell** [odell/rose#3]
Preliminary testing shows promise. Some details need to be worked out with the HF solver parameters and the initial conditions.

**Comment by kylegodbey** [comment]
Is this in a branch, or just being worked on locally?

**Comment by odell** [comment]
Just locally. I'll push to the develop branch soon.

**Comment by odell** [comment]
Coulomb support has been pushed to the `develop` branch.

**Comment by odell** [comment]
Basic functionality tests have passed.
