### ISSUE TITLE
Enable the user to save the emulator object.

### ISSUE THREAD

**Issue by odell** [odell/rose#4]
Currently, the plan is to use the `pickle` library.

**Comment by kylegodbey** [comment]
There are a few things that a use might want to save, so we can think if we want to add this functionality to the 1) RBM object, 2) EIM interaction, and 3) overall scattering emulator.

The most important thing is making sure the final object that takes the input and model parameters and outputs observables is savable and easily distributed without having to define too much. Even if the saved emulator needs to "warm-up" by running a few helper functions, it's much nicer to abstract that away for the end user.

We probably want to add class functions called `save` or `export` that:
```
if(given path/filename):
  uses pickle.dump and returns error code
else:
  uses pickle.dumps and return bytes object
```

An appropriate `load` or `import` class function will do the reverse.

**Comment by odell** [comment]
`save` and `load` methods have been added to `ReducedBasisEmulator` and `ScatteringAmplitudeEmulator`. `save` is an instance method and `load` is a class method. Basic functionality tests for both classes have successfully passed.

**Comment by odell** [comment]
See `develop` branch.

**Comment by pabggpnMSU** [comment]
Fantastic, thank you Daniel!

Would it be possible also to add a functionality in where the high fidelity solutions used for training can also be saved? I am thinking of the following situation:

1) User wants an emulator with 4, 8, and 12 basis for the wave functions to make a CAT plot.
2) User solves the high fidelity solver 50 times for 50 parameters chosen from the latin hyper cube. User then saves the 50 solutions that were computed only once.
3) User creates a "sae" with 4 basis by taking the first 4 PC out of the 50. Does the same with 8 and 14 PC without having to recompute the 50 solutions.
4) User saves those four emulators such that they don't need to create them again (implemented already!).

**Comment by odell** [comment]
So, that capability is already implemented in part. The solutions are saved with the object. What needs to be added is the capability to supply those solutions when instantiating another `ReducedBasisEmulator`.

**Comment by odell** [comment]
Currently, my plan is to allow the user to supply a `RelativeBasis` object. See `basis.py`.

**Comment by pabggpnMSU** [comment]
Ok ok perfect!! Yes, exactly, we would like to have the "emulated object" and the "training solutions object" to be separable. That also will help in the direction of the user providing its own solver.

**Comment by pabggpnMSU** [comment]
Comment by Kyle (typing it here so we don't forget): When storing the emulator, it would be good to also store information of the version of ROSE that was used to create it. That way if in the future we keep releasing updates and one of them breaks something from previous versions people can be aware and not try to use incompatible saved emulators from withered ROSEs.

**Comment by odell** [comment]
`rose` version number is now set as `__version__` in `__init__.py` (exclusively). It's also dynamically updated in `pyproject.toml`.

**Comment by odell** [comment]
Do we want to have the `save` functions automatically append the version number to the filename?

**Comment by odell** [comment]
If I add a `version` attribute to `ReducedBasisEmulator` that is just `rose.__version__`:
• Whenever the user loads a saved RBE (or SAE), the version information will be accessible.
• Will this actually work? Seems circular...

**Comment by odell** [comment]
The above suggestion doesn't work. Not surprising. I don't want to let this hold up progress, so I propose that we let the user deal with versions. `rose` has `__version__`, so they can always access it a append it to the filenames of their saved emulators.

**Comment by odell** [comment]
Implemented and tested. 👍
