### ISSUE TITLE
Controlling the high fidelity solver complexity

### ISSUE THREAD

**Issue by pabggpnMSU** [odell/rose#8]
The high fidelity solver for ROSE uses the RK45 initial value problem solver from python as default with the following relative and absolute tolerance:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/78561223/227735973-4ff42550-ebc0-43ea-8adb-cfdb3cac9a4a.png">

It would be nice if the user could control that if they want to use something else than the default, not only for speeding up the training/testing cycles, but to create the Computational Accuracy vs Time plots: 

<img width="594" alt="image" src="https://user-images.githubusercontent.com/78561223/227736007-6c3024c9-5bab-4d44-b754-ca150b910a8f.png">

**Comment by odell** [comment]
This is now available via the optional `hf_tols` keyword when instantiating a `ReducedBasisEmulator` object.
